version: "3.5"

services:
  web:
    restart: always
    image: webdevops/php-nginx:8.0
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/web

  webpack:
#    restart: always
    container_name: webpack
    image: node:14
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    ports:
      - 8080:8080
    #  environment:
     #   - NODE_ENV=development
    command: sh -c "npm install && npm run build"
