version: "3.5"

services:
  webpack:
    restart: always
    container_name: webpack
    image: node:14
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    ports:
      - 8080:8080
    #  environment:
     #   - NODE_ENV=development
    command: sh -c "npm install && npm run build && npm start"
